### ISSUE TITLE
[Bilibili] 网站变更致番剧失效

### ISSUE THREAD

**Issue by Liqianyu** [ArchieMeng/xbmc-kodi-private-china-addons#1]
现在番剧 (https://www.bilibili.com/bangumi/play/ss) 页面里已经没有'window.__INITIAL_STATE__='这个对象了？
附加组件打开任何番剧（新番、国产动画、电影、电视剧、纪录片）标题时会发生报错。

以下为日志（代码有修改所以行数不同）
> error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'json.decoder.JSONDecodeError'>
>                                                    Error Contents: Expecting value: line 1 column 1 (char 0)
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili/addon.py", line 3060, in <module>
>                                                        plugin.run()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 338, in run
>                                                        items = self._dispatch(self.request.path)
>                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 312, in _dispatch
>                                                        listitems = view_func(**items)
>                                                                    ^^^^^^^^^^^^^^^^^^
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili/addon.py", line 2306, in sources
>                                                        sources = get_sources(url)
>                                                                  ^^^^^^^^^^^^^^^^
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bilibili/addon.py", line 1790, in get_sources
>                                                        j = json.loads(vjson)
>                                                            ^^^^^^^^^^^^^^^^^
>                                                      File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/__init__.py", line 346, in loads
>                                                        return _default_decoder.decode(s)
>                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 337, in decode
>                                                        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
>                                                        raise JSONDecodeError("Expecting value", s, err.value) from None
>                                                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>                                                    -->End of Python script error report<--

**Comment by ArchieMeng** [comment]
了解。这个我有空看一下。挺久没更新了，挺多问题的。。。感谢指出。

**Comment by crazyfeezy** [comment]
老哥，请问现在还有没有适配kodi17.6的b站插件，我已有的插件都无法正常观看了

**Comment by ArchieMeng** [comment]
kodi 17.6好像是python2的吧。用py2的分支应该可以吧？实在不行，合并py3上B站插件的修改上去，应该能顶一顶。
番剧报错的问题我看过了，它这部分功能要重构，所以要花点时间改的。

**Comment by crazyfeezy** [comment]
多谢老哥回复，我没接触过编程，可能需要研究研究了🥲

**Comment by ArchieMeng** [comment]
> 老哥，请问现在还有没有适配kodi17.6的b站插件，我已有的插件都无法正常观看了

能提供一下你kodi的运行环境吗？我手上没有这么老的kodi版本。
或者，建议升级到kodi19以上。未来还是多以Python3为主了。还是说，你有很多要用的插件还是只有Python2的？

**Comment by crazyfeezy** [comment]
主要是俺的设备太古老了，只能用17.6😭，这是俺的运行日志https://paste.kodi.tv/iperocupup
